config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

   root 'home#index'

   resources :news
   resources :local_news, controller: 'news', type: 'LocalNews' 
   resources :national_news, controller: 'news', type: 'NationalNews' 
   resources :international_news, controller: 'news', type: 'InternationalNews'
   resources :general_news, controller: 'news', type: 'GeneralNews' 
   resources :upcoming_news, controller: 'news', type: 'UpcomingNews' 
   resources :trending_news, controller: 'news', type: 'TrendingNews'
   resources :miscellanious_news, controller: 'news', type: 'MiscelleneousNews'

   resources :galleries
   resources :artists, controller: 'galleries', type: 'Artist' 
   resources :models, controller: 'galleries', type: 'Model' 

   resources :beauty_and_sex
   resources :beauties, controller: 'beauty_and_sex', type: 'Beauty' 
   resources :sexes, controller: 'beauty_and_sex', type: 'Sex'
   resources :teen_health, controller: 'beauty_and_sex', type: 'TeenHealth'

   resources :gossips
   resources :biographies
   resources :music_and_videos
   resources :horoscopes
   resources :cartoons

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/artist.rb
class Artist < Gallery
end

app/models/beauty.rb
class Beauty < BeautyAndSex
end

app/models/biography.rb
class Biography < ActiveRecord::Base

	belongs_to :category
	has_attached_file :image,
    styles: { medium: "1000x1000>", thumb: "1000x1000>" },
    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image,
    content_type: /\Aimage\/.*\Z/
  has_attached_file :video#, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :video, :content_type => ["video/mp4", "video/mov","image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/breaking_news.rb
class BreakingNews < News
end

app/models/cartoon.rb
class Cartoon < ActiveRecord::Base

	has_attached_file :image,
    styles: { medium: "1000x1000>", thumb: "1000x1000>" },
    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image,
    content_type: /\Aimage\/.*\Z/
  has_attached_file :video#, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :video, :content_type => ["video/mp4", "video/mov","image/jpg", "image/jpeg", "image/png", "image/gif"]


end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :news
  has_many :gossips
  has_many :beauty_and_sexes
  has_many :galleries
  has_many :biographies
  delegate :local_news, :national_news, :internationa_news, to: :news
  delegate :artists, :models, to: :gossips
  delegate :beauties, :sexes,:teen_health, to: :beauty_and_sexes
end

app/models/event.rb
class Event < ActiveRecord::Base

	has_attached_file :guest_image,
    styles: { medium: "1000x1000>", thumb: "1000x1000>" },
    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :guest_image,
    content_type: /\Aimage\/.*\Z/

  has_attached_file :host_image,
	  styles: { medium: "1000x1000>", thumb: "1000x1000>" },
	  default_url: "/images/:style/missing.png"
  validates_attachment_content_type :host_image,
    content_type: /\Aimage\/.*\Z/

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  
  belongs_to :category
  has_attached_file :image,
    styles: { medium: "1000x1000>", thumb: "1000x1000>" },
    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image,
    content_type: /\Aimage\/.*\Z/
  has_attached_file :video#, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :video, :content_type => ["video/mp4", "video/mov","image/jpg", "image/jpeg", "image/png", "image/gif"]


  belongs_to :category
  self.inheritance_column = :gallery_type
  scope :artists, -> { where(gallery_type: 'Artist') } 
  scope :models, -> { where(gallery_type: 'Model') } 

  def self.gallery_types
    %w(Artist Model)
  end

end

# class Artist < Gossip; end 
# class Model < Gossip; end 

app/models/general_news.rb
class GeneralNews < News
end

app/models/gossip.rb
class Gossip < ActiveRecord::Base

	has_attached_file :image,
    styles: { medium: "1000x1000>", thumb: "1000x1000>" },
    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image,
    content_type: /\Aimage\/.*\Z/
  has_attached_file :video#, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :video, :content_type => ["video/mp4", "video/mov","image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/models/horoscope.rb
class Horoscope < ActiveRecord::Base

	has_attached_file :image,
    styles: { medium: "1000x1000>", thumb: "1000x1000>" },
    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image,
    content_type: /\Aimage\/.*\Z/
  has_attached_file :video#, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :video, :content_type => ["video/mp4", "video/mov","image/jpg", "image/jpeg", "image/png", "image/gif"]

	def self.types
	  %w(Aries Tauraus Gemini Cancer Leo Virgo Libra Scorpio Saggitarius Capricorn Aquarius Pisces)
	end

end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :music_and_video
	has_attached_file :image,
    styles: { medium: "1000x1000>", thumb: "1000x1000>" },
    default_url: "/images/:style/missing.png"

end

app/models/local_news.rb
class LocalNews < News
end

app/models/model.rb
class Model < Gallery
end

app/models/national_news.rb
class NationalNews < News
end

app/models/news.rb
class News < ActiveRecord::Base
	belongs_to :category 
	self.inheritance_column = :news_type

	has_attached_file :image,
    styles: { medium: "1000x1000>", thumb: "1000x1000>" },
    default_url: "/images/:style/missing.png"

  validates_attachment_content_type :image,
    content_type: /\Aimage\/.*\Z/
  has_attached_file :video#, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :video, :content_type => ["video/mp4", "video/mov","image/jpg", "image/jpeg", "image/png", "image/gif"]

	scope :local_news, -> { where(news_type: 'LocalNews') } 
	scope :national_news, -> { where(news_type: 'NationalNews') } 
	scope :international_news, -> { where(news_type: 'InternationalNews') }

	def self.news_type
    %w(LocalNews NationalNews InternationalNews GeneralNews MiscelleneousNews UpcomingNews TrendingNews BreakingNews)
  end

  def self.search(query)
	  where("heading ILIKE ?", "%#{query}%") 
	  where("description ILIKE ?", "%#{query}%")
	end
end

app/models/sex.rb
class Sex < BeautyAndSex
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to: :categories
end

app/models/teen_health.rb
class TeenHealth < BeautyAndSex
end

app/views/layouts/application.html.erb
<!Doctype html>
<html>
<head>
  <title>Muzbuzz-Home Page</title>
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css' %>
  <%= javascript_include_tag 'https://code.jquery.com/jquery-2.1.4.min.js' %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
  <style type="text/css">
    .grid__sizer,
    .grid__item {
      width: 100%;
    }
    .filter__item{
      margin: 0 1%;
    }
  </style>
 </head>
 <body>
   <div class="container-fluid no-padding">
   <div class="row" style="margin:0;">
         <%= render :partial => 'shared/nav_bar' %>
      </div>
    </div>
    <%= yield %>
</div>
<%= render 'shared/footer' %>

app/views/shared/_footer.html.erb
</div>
</div>
<div id="footer">
	<div class="container">
		<div class="row">
			<div class="col-lg-6 col-lg-offset-3">
					<p class="copyright"></p>
			</div>
		</div>
	</div>
	</div>
		<script type="text/javascript">
		$('.rst-pageline-slider').owlCarousel({
			 autoPlay: 3000,
			singleItem: true,
			pagination : false,
			navigation : true,
			navigationText : ['<i class="fa fa-long-arrow-left"></i>','<i class="fa fa-long-arrow-right"></i>'],
		});
	</script>
	<script type="text/javascript">
		$(document).ready(function() {
		    $("#owl-bolly").owlCarousel({
		  		items : 5,

		  	});	
		});
		$('.rst-hotnews').owlCarousel({
			paginationSpeed: 300,
			singleItem: true,
			pagination : true,
			navigation : false,
			autoPlay: true,
		});
	</script>
		
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55234356-2', 'auto');
  ga('send', 'pageview');

</script>
</body>
</htmls>

app/views/shared/_nav_bar.html.erb
<div class="col-md-12 no-padding">
<nav class="navbar navbar-default navbar-custom" role="navigation" style="margin-bottom:0;">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
               <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button> <a class="navbar-brand" href="#" style="  padding-top:23px;">Muzbuzz-Logo</a>
          </div>
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active">
                <a href="#">Home</a>
              </li>
              <li class="dropdown">
                <a href="<%= news_index_path %>">News</a>
              </li>
              <li>
                <a href="<%= galleries_path %>">Gallery</a>
              </li>
              <li>
                <a href="<%= music_and_videos_path %>">Music Videos</a>
              </li>
              <li>
                <a href="<%= gossips_path %>">Gossips</a>
              </li>
              <li>
                <a href="<%= beauty_and_sex_index_path %>">Beauty & Sex</a>
              </li>
              <li>
                <a href="<%= biographies_path %>">Biography</a>
              </li>
              <li>
                <a href="<%= cartoons_path %>">Cartoons</a>
              </li>
              <li>
                <a href="<%= horoscopes_path %>">Horoscopes</a>
              </li>
            </ul>
          </div>
</nav>
</div>